### PR TITLE
Prevent execute from being called multiple times

### PR DESCRIPTION
**Pull request by arosenb2**
Keydown can allow double fire, which could be a problem for running execute commands. See [this article](http://www.quirksmode.org/dom/events/keys.html) for more information.

### CODE REVIEW

**Comment by davidsawyer** [comment]
:+1:

**Comment by sheehan** [comment]
Thanks. This is a good idea, but it seems to break the "Meta+return" binding. There's some mention [here](https://github.com/jeresig/jquery.hotkeys#meta-and-hyper-keys) that meta doesn't work with keyup. I'll look into it a bit more.

**Comment by arosenb2** [comment]
Perhaps `keypress` instead?

**Comment by sheehan** [comment]
Sorry I've been busy with something else. Doesn't it say in the quirksmode article that keypress has the same issue as keydown?

**Comment by arosenb2** [comment]
Sadly yes. Maybe keeping `keydown` would be better, but having it check when the last time that run was called and allow allow it to run if it had been more than like 1-2 seconds. I'll see what I can come up with when I get some free cycles.

**Comment by sheehan** [comment]
It may be that we can use `keyup` and just bind to `return` and then check the event for `ctrl` or `meta`. I'll test that out when I get a chance.

**Pull request closed without merging**
